Csv import
near/near-analytics pull request #22
Opened 2021-11-02 10:40 UTC by jschintz

Manual process to import apps info.  
- Imports csv file of ecosystem entities
- Overloads collect statement to gather csv.

2021-11-02 19:00 UTC, jschintz commented
Manually Import File of Ecosystem Entity Members

2021-11-04 12:34 UTC, frol requested changes
* [ ] Before we merge it, can you show how will you use this data? How does it help you to have this raw dump of data in the database?
* [ ] Clean up your PR:
  * [ ] Remove `.DS_Store` files
  * [ ] Address the comments I left at the specific places

2021-11-04 12:34 UTC, frol commented on aggregations/sql_aggregations.py
> +
Don't introduce unnecessary changes

2021-11-04 12:34 UTC, frol commented on aggregations/db_tables/near_ecosystem_entities.py
> +#    @staticmethod
Clean up your code before submitting the code for review

2021-11-04 12:34 UTC, frol commented on aggregations/db_tables/near_ecosystem_entities.py
> +        # All fields are text, of varying length
How does this comment help?

2021-11-04 13:50 UTC, jschintz commented
Thanks, Vlad

I just adjusted those changes you asked for.
Below is how we intend to use the file.  Would you prefer to talk it
through with myself & Neil?

Thanks,
James

The csv contains information about partners that is currently not on the
chain, and stored in the ecosystem map repo. We are currently working with
the ES team to create a CI that will create this json. The reason for the
temporary method is to unblock the aggregations that are reliant on the app
data.The data will be used to aggregate the accounts data by app as is
needed for 4/5 proposed visualizations for the new stats site. The
ecosystem data contains the contract_ids needed to make this aggregation
and additional information such as the App name, website links etc that
Erik has requested to be included in the visualizations & tooltips. For
reference, please see the designs
<https://www.figma.com/proto/Lfw8WzdlqP63QdQj2C0NwM/stats.near.org-designs?node-id=1%3A441&scaling=min-zoom&page-id=0%3A1>
.Even without the visualizations, any app level aggregations will need to
related to an app name and associated contracts, as some apps have more
than one parent contract listed.The app aggregations will take the form of
a single additional table added to the NEAR analytics database that will
contain daily_accounts_per_app_count in a similar format to
daily_transactions_per_account_count table that has already been created by
the NEAR team.

On Thu, Nov 4, 2021 at 8:34 AM Vlad Frolov ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
>    - Before we merge it, can you show how will you use this data? How
>    does it help you to have this raw dump of data in the database?
>    - Clean up your PR:
>       - Remove .DS_Store files
>       - Address the comments I left at the specific places
>
> ------------------------------
>
> In aggregations/sql_aggregations.py
> <https://github.com/near/near-analytics/pull/22#discussion_r742787920>:
>
> > @@ -62,6 +62,7 @@ def store(self, parameters: list):
>                  except psycopg2.errors.UniqueViolation:
>                      self.analytics_connection.rollback()
>
> +
>
> Don't introduce unnecessary changes
> ------------------------------
>
> In aggregations/db_tables/near_ecosystem_entities.py
> <https://github.com/near/near-analytics/pull/22#discussion_r742788511>:
>
> > +#overload collect method defined in sql_aggregations
> +#    @staticmethod
>
> Clean up your code before submitting the code for review
> ------------------------------
>
> In aggregations/db_tables/near_ecosystem_entities.py
> <https://github.com/near/near-analytics/pull/22#discussion_r742789185>:
>
> > @@ -0,0 +1,47 @@
> +import csv
> +from ..sql_aggregations import SqlAggregations
> +
> +
> +class NearEcosystemEntities(SqlAggregations):
> +    @property
> +    def sql_create_table(self):
> +        # All fields are text, of varying length
>
> How does this comment help?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/near/near-analytics/pull/22#pullrequestreview-797675212>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABERYPMYAU4MX5FJYBOSRC3UKJ4ULANCNFSM5HGD2UBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-05 13:35 UTC, frol approved these changes
I still don't see how this table will help you in any way given that it mostly lacks the account/contract ids anyway.

@telezhnaya Let's merge it as is, noting to ourselves that this table is a temporary solution.

@jschintz On the next iterations I would prefer to only store cleaned data to the near-analytics database.

2021-11-05 13:42 UTC, merged